# Fix 2: E2E Tests Environment
# File: .github/workflows/e2e-tests.yml

name: E2E Tests

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - '.github/**'
      - 'installer/**'
      - 'tools/**'
  push:
    branches: [main, develop]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - '.github/**'
      - 'installer/**'
      - 'tools/**'
  workflow_dispatch:

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: backend/requirements*.txt

      # FIX 1: Add system dependencies check
      - name: Update system packages
        run: |
          sudo apt-get update || echo "Failed to update apt, continuing..."

      - name: Determine Playwright version
        id: pwver
        working-directory: ./frontend
        run: |
          VERSION=$(node -p "require('./package.json').devDependencies['@playwright/test'].replace(/^\^/, '')")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          MINOR=$(node -p "require('./package.json').devDependencies['@playwright/test'].replace(/^\^/, '').split('.').slice(0,2).join('.')")
          echo "minor=$MINOR" >> $GITHUB_OUTPUT
          echo "Playwright version: $VERSION"

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ steps.pwver.outputs.version }}
          restore-keys: |
            playwright-${{ runner.os }}-${{ steps.pwver.outputs.minor }}
            playwright-${{ runner.os }}-

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      # FIX 2: Install Playwright with system dependencies explicitly
      - name: Install Playwright browsers with dependencies
        working-directory: ./frontend
        run: |
          echo "Installing Playwright browsers..."
          npx playwright install chromium --with-deps
          echo "Verifying Playwright installation..."
          npx playwright --version

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # FIX 3: Add database initialization
      - name: Prepare data directory
        run: mkdir -p ./data

      # FIX 4: Initialize database with migrations before seeding
      - name: Initialize database
        working-directory: ./backend
        run: |
          echo "Running Alembic migrations..."
          python -c "from backend.run_migrations import run_migrations; run_migrations()" || echo "Migration warning (may already be up-to-date)"

      - name: Seed test data
        run: |
          echo "Seeding E2E test data..."
          python backend/seed_e2e_data.py

      # FIX 5: Add health check before starting tests
      - name: Start backend in background
        env:
          DISABLE_STARTUP_TASKS: '1'
          CSRF_ENABLED: '0'
          AUTH_MODE: permissive
          SERVE_FRONTEND: '1'
          DATABASE_URL: sqlite:///./data/student_management.db
        run: |
          echo "Starting backend server..."
          python -m uvicorn backend.main:app --host 127.0.0.1 --port 8000 &
          echo $! > backend.pid
          sleep 5

          # Wait for backend to be ready with better error handling
          echo "Waiting for backend health check..."
          for i in {1..30}; do
            if curl -sf http://127.0.0.1:8000/health > /dev/null 2>&1; then
              echo "✅ Backend is ready (attempt $i/30)"
              break
            fi
            if [ $i -eq 30 ]; then
              echo "❌ Backend failed to start within 30 seconds"
              if [ -f backend.pid ]; then
                echo "Backend process status:"
                ps aux | grep $(cat backend.pid) || echo "Process not found"
              fi
              exit 1
            fi
            echo "⏳ Waiting for backend... ($i/30)"
            sleep 1
          done

      - name: Run E2E tests
        working-directory: ./frontend
        env:
          PLAYWRIGHT_BASE_URL: http://127.0.0.1:8000
        run: |
          echo "=== Sanity check: curl /login ==="
          curl -I http://127.0.0.1:8000/login || echo "Login endpoint check failed"

          echo "=== Sanity check: curl / ==="
          curl -I http://127.0.0.1:8000/ || echo "Root endpoint check failed"

          echo "=== Running Playwright E2E tests ==="
          npm run e2e

      - name: Kill backend
        if: always()
        run: |
          if [ -f backend.pid ]; then
            echo "Stopping backend (PID: $(cat backend.pid))..."
            kill $(cat backend.pid) 2>/dev/null || echo "Backend already stopped"
            rm backend.pid
          fi

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: |
            frontend/playwright-report/
            frontend/test-results/
          retention-days: 30
          if-no-files-found: ignore

      # FIX 6: Add logs for debugging
      - name: Upload backend logs (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-backend-logs
          path: backend/logs/
          retention-days: 7
          if-no-files-found: ignore
