"""Schema drift detection utility.

Run this script to compare the current database schema against the SQLAlchemy
models defined in `backend.models`. It performs an autogenerate diff similar
to `alembic revision --autogenerate` but without creating a migration file.

Usage (from repository root or backend directory):

    python -m backend.tools.check_schema_drift
    python -m backend.tools.check_schema_drift --fail-on-drift

Exit codes:
  0 = No drift detected
  1 = Drift detected (and --fail-on-drift supplied) or unexpected error

Designed for CI integration so that inadvertent direct DB changes or missing
Alembic revisions are caught early.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, List

from alembic.config import Config
from alembic.migration import MigrationContext
from alembic.script import ScriptDirectory
from sqlalchemy import create_engine


def _load_db_url() -> str:
    """Resolve the database URL using backend config settings, falling back to local SQLite.

    We avoid importing heavy modules (FastAPI app) and only pull what we need.
    """
    try:
        from backend.config import settings  # type: ignore

        return settings.database_url
    except Exception:
        # Fallback consistent with models.init_db default
        return "sqlite:///student_management.db"


def _load_metadata():
    """Import models and return the Base.metadata."""
    from backend import models  # type: ignore

    return models.Base.metadata


def detect_drift() -> List[Any]:
    """Perform autogenerate diff and return a list of differences.

    Each element in the returned list is an Alembic diff directive describing
    a schema change that would be generated (e.g., AddTable, AddColumn).
    """
    db_url = _load_db_url()
    engine = create_engine(db_url)
    metadata = _load_metadata()

    with engine.connect() as connection:
        # Configure MigrationContext with connection + metadata for autogenerate
        mc = MigrationContext.configure(connection)

        # Compare database vs metadata
        diffs = []  # type: List[Any]
        try:
            from alembic.autogenerate import compare_metadata

            diffs = compare_metadata(mc, metadata) or []
        except Exception as e:  # pragma: no cover - defensive
            print(f"ERROR: failed during compare_metadata: {e}", file=sys.stderr)
            return [f"compare_error: {e}"]

    return diffs


def _format_diff_item(item: Any) -> str:
    """Human readable formatting for a diff directive."""
    try:
        if isinstance(item, tuple) and item:
            directive = item[0]
            return f"{directive}: {item[1:]}"
        return repr(item)
    except Exception:  # pragma: no cover
        return repr(item)


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Check for schema drift against Alembic models.")
    parser.add_argument("--fail-on-drift", action="store_true", help="Return non-zero exit code if drift detected.")
    args = parser.parse_args(argv)

    diffs = detect_drift()

    if not diffs:
        print("✅ No schema drift detected (database schema matches models).")
        return 0

    print("⚠️ Schema drift detected - the following changes would be autogenerated:")
    for item in diffs:
        print("  -", _format_diff_item(item))

    if args.fail_on_drift:
        print("❌ Failing due to --fail-on-drift.")
        return 1
    else:
        print("(Run with --fail-on-drift to make this non-zero in CI.)")
        return 0


if __name__ == "__main__":  # pragma: no cover - script entry point
    raise SystemExit(main())
