"""Use timezone-aware datetime for User timestamps

Revision ID: 039d0af51aab
Revises: 9a1d2b3c4d56
Create Date: 2025-10-30 22:39:13.174765

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "039d0af51aab"
down_revision: Union[str, None] = "9a1d2b3c4d56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _index_exists(table_name: str, index_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    indexes = inspector.get_indexes(table_name)
    return any(idx.get("name") == index_name for idx in indexes)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN directly, but we can add the indexes
    # The datetime columns already exist and SQLite is flexible with timezone storage
    with op.batch_alter_table("users", schema=None) as batch_op:
        # Drop old index and recreate with unique constraint
        if _index_exists("users", "ix_users_email"):
            batch_op.drop_index("ix_users_email")
        if not _index_exists("users", "ix_users_email"):
            batch_op.create_index("ix_users_email", ["email"], unique=True)
        # Add new indexes
        if not _index_exists("users", "ix_users_created_at"):
            batch_op.create_index("ix_users_created_at", ["created_at"], unique=False)
        if not _index_exists("users", "ix_users_id"):
            batch_op.create_index("ix_users_id", ["id"], unique=False)
        if not _index_exists("users", "ix_users_updated_at"):
            batch_op.create_index("ix_users_updated_at", ["updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        if _index_exists("users", "ix_users_updated_at"):
            batch_op.drop_index("ix_users_updated_at")
        if _index_exists("users", "ix_users_id"):
            batch_op.drop_index("ix_users_id")
        if _index_exists("users", "ix_users_created_at"):
            batch_op.drop_index("ix_users_created_at")
        if _index_exists("users", "ix_users_email"):
            batch_op.drop_index("ix_users_email")
        if not _index_exists("users", "ix_users_email"):
            batch_op.create_index("ix_users_email", ["email"], unique=False)
    # ### end Alembic commands ###
