"""add refresh tokens table

Revision ID: ab12cd34ef56
Revises: 039d0af51aab
Create Date: 2025-11-10 20:47:00.000000

"""

from typing import Sequence, Union

# Removed unused alembic/op and sqlalchemy imports; this migration is a no-op
# (archived) and original content is stored under migrations/archived/.


# revision identifiers, used by Alembic.
revision: str = "ab12cd34ef56"
down_revision: Union[str, Sequence[str], None] = "039d0af51aab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # This migration has been archived and replaced by a canonical autogenerated
    # migration (ffedcba12345). To avoid duplicate DDL we make this migration a
    # no-op. The original archived content is stored in
    # migrations/archived/ab12cd34ef56_add_refresh_tokens_table.py
    pass


def downgrade() -> None:
    # No-op downgrade because the canonical migration handles table removal.
    pass
