"""Add password_change_required field to users table

Revision ID: d377f961aa1f
Revises: 00c146dcf611
Create Date: 2025-11-23 21:57:42.942410

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d377f961aa1f"
down_revision: Union[str, None] = "00c146dcf611"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_exists(table_name: str, column_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col["name"] for col in inspector.get_columns(table_name)]
    return column_name in columns


def _index_exists(table_name: str, index_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    indexes = inspector.get_indexes(table_name)
    return any(idx.get("name") == index_name for idx in indexes)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _column_exists("users", "password_change_required"):
        op.add_column(
            "users",
            sa.Column("password_change_required", sa.Boolean(), nullable=False, server_default=sa.text("FALSE")),
        )
    index_name = op.f("ix_users_password_change_required")
    if _column_exists("users", "password_change_required") and not _index_exists("users", index_name):
        op.create_index(index_name, "users", ["password_change_required"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    index_name = op.f("ix_users_password_change_required")
    if _index_exists("users", index_name):
        op.drop_index(index_name, table_name="users")
    if _column_exists("users", "password_change_required"):
        op.drop_column("users", "password_change_required")
    # ### end Alembic commands ###
