# d:\SMS\student-management-system\scripts\setup_git_hooks.ps1
<#
.SYNOPSIS
    Sets up Git hooks for the repository.
.DESCRIPTION
    Installs the pre-commit hook to enforce version format (Policy 2).
    Backs up existing hooks if found.
#>

$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$rootDir = Split-Path -Parent $scriptDir
$hooksDir = Join-Path $rootDir ".git\hooks"
$preCommitPath = Join-Path $hooksDir "pre-commit"

# Ensure .git/hooks exists
if (-not (Test-Path $hooksDir)) {
    Write-Host "Error: .git directory not found. Are you in the repository root?" -ForegroundColor Red
    exit 1
}

# Handle existing hook (chaining)
$legacyHookPath = Join-Path $hooksDir "pre-commit-legacy"

if (Test-Path $preCommitPath) {
    $existingContent = Get-Content $preCommitPath -Raw
    if ($existingContent -notmatch "Auto-generated by scripts/setup_git_hooks.ps1") {
        Write-Host "⚠️  Existing pre-commit hook found. Renaming to pre-commit-legacy to preserve functionality." -ForegroundColor Yellow
        Move-Item $preCommitPath -Destination $legacyHookPath -Force
    }
}

$hookContent = @'
#!/bin/bash
# Pre-commit hook
# Enforces Policy 2 (Version Format) and Policy 5 (COMMIT_READY)
# Auto-generated by scripts/setup_git_hooks.ps1

echo "🔒 Running Pre-Commit Validation..."

# Determine hooks directory
HOOKS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# 1. Validate Version Format (Layer 4)
# Uses the standalone validator script
if [ -f "scripts/validate_version_format.ps1" ]; then
    pwsh -Command "& 'scripts/validate_version_format.ps1'"
    if [ $? -ne 0 ]; then
        echo "❌ Version format validation FAILED. Commit blocked."
        exit 1
    fi
else
    echo "⚠️ Warning: scripts/validate_version_format.ps1 not found. Skipping version check."
fi

# 2. Run legacy/framework hooks if they exist
LEGACY_HOOK="$HOOKS_DIR/pre-commit-legacy"
if [ -f "$LEGACY_HOOK" ]; then
    echo "🔄 Running legacy pre-commit hooks..."
    "$LEGACY_HOOK" "$@"
    EXIT_CODE=$?
    if [ $EXIT_CODE -ne 0 ]; then
        echo "❌ Legacy hooks failed (Exit Code: $EXIT_CODE)."
        echo "   💡 Tip: Run 'pre-commit run --all-files' to see details and auto-fix issues."
        exit $EXIT_CODE
    fi
fi

exit 0
'@

# Write the hook file
# Use [IO.File] to ensure LF line endings (bash friendly) and UTF-8 without BOM
$hookContent = $hookContent -replace "`r`n", "`n"
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($preCommitPath, $hookContent, $utf8NoBom)

# Attempt to make executable (Git Bash/Unix compatibility)
try {
    git update-index --chmod=+x .git/hooks/pre-commit 2>$null
} catch {
    # Ignore if git command fails
}

Write-Host "✅ Git pre-commit hook installed successfully at $preCommitPath" -ForegroundColor Green
Write-Host "   - Enforces v1.x.x version format"
