"""Add full-text search indexes for student search

Revision ID: 3af743932574
Revises: a02276d026d0
Create Date: 2026-01-25 11:21:55.653596

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3af743932574"
down_revision: Union[str, None] = "a02276d026d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        # SQLite cannot ALTER columns the way Alembic generated below; skip for test DBs.
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "export_jobs",
        "total_records",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("'0'"),
    )
    op.alter_column(
        "export_jobs",
        "scheduled",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("'false'"),
    )
    op.alter_column(
        "export_jobs",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.create_index(op.f("ix_export_jobs_created_at"), "export_jobs", ["created_at"], unique=False)
    op.create_index(op.f("ix_export_jobs_status"), "export_jobs", ["status"], unique=False)
    op.alter_column(
        "import_export_history",
        "timestamp",
        existing_type=sa.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.create_index(
        op.f("ix_import_export_history_operation_type"), "import_export_history", ["operation_type"], unique=False
    )
    op.create_index(
        op.f("ix_import_export_history_resource_type"), "import_export_history", ["resource_type"], unique=False
    )
    op.alter_column(
        "import_jobs",
        "successful_rows",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("'0'"),
    )
    op.alter_column(
        "import_jobs", "failed_rows", existing_type=sa.INTEGER(), nullable=True, existing_server_default=sa.text("'0'")
    )
    op.alter_column(
        "import_jobs",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.create_index(op.f("ix_import_jobs_created_at"), "import_jobs", ["created_at"], unique=False)
    op.create_index(op.f("ix_import_jobs_status"), "import_jobs", ["status"], unique=False)
    op.alter_column(
        "import_rows",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.create_index(op.f("ix_import_rows_import_job_id"), "import_rows", ["import_job_id"], unique=False)
    op.create_index(op.f("ix_import_rows_status"), "import_rows", ["status"], unique=False)
    op.alter_column("permissions", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("ix_permissions_key"), table_name="permissions")
    op.create_index(op.f("ix_permissions_key"), "permissions", ["key"], unique=True)
    # ### end Alembic commands ###

    # Add search optimization indexes
    op.create_index("ix_student_status", "student", ["status"], unique=False)
    op.create_index("ix_student_created_at", "student", ["created_at"], unique=False)
    op.create_index("ix_student_updated_at", "student", ["updated_at"], unique=False)
    op.create_index("ix_enrollment_enrollment_type", "enrollment", ["enrollment_type"], unique=False)
    op.create_index("ix_student_search_composite", "student", ["status", "created_at", "id"], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop search optimization indexes
    op.drop_index("ix_student_search_composite", table_name="student")
    op.drop_index("ix_enrollment_enrollment_type", table_name="enrollment")
    op.drop_index("ix_student_updated_at", table_name="student")
    op.drop_index("ix_student_created_at", table_name="student")
    op.drop_index("ix_student_status", table_name="student")

    op.drop_index(op.f("ix_permissions_key"), table_name="permissions")
    op.create_index(op.f("ix_permissions_key"), "permissions", ["key"], unique=False)
    op.alter_column("permissions", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.drop_index(op.f("ix_import_rows_status"), table_name="import_rows")
    op.drop_index(op.f("ix_import_rows_import_job_id"), table_name="import_rows")
    op.alter_column(
        "import_rows",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.drop_index(op.f("ix_import_jobs_status"), table_name="import_jobs")
    op.drop_index(op.f("ix_import_jobs_created_at"), table_name="import_jobs")
    op.alter_column(
        "import_jobs",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "import_jobs", "failed_rows", existing_type=sa.INTEGER(), nullable=False, existing_server_default=sa.text("'0'")
    )
    op.alter_column(
        "import_jobs",
        "successful_rows",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("'0'"),
    )
    op.drop_index(op.f("ix_import_export_history_resource_type"), table_name="import_export_history")
    op.drop_index(op.f("ix_import_export_history_operation_type"), table_name="import_export_history")
    op.alter_column(
        "import_export_history",
        "timestamp",
        existing_type=sa.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.drop_index(op.f("ix_export_jobs_status"), table_name="export_jobs")
    op.drop_index(op.f("ix_export_jobs_created_at"), table_name="export_jobs")
    op.alter_column(
        "export_jobs",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "export_jobs",
        "scheduled",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("'false'"),
    )
    op.alter_column(
        "export_jobs",
        "total_records",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("'0'"),
    )
    # ### end Alembic commands ###
