"""Add permissions and roles_permissions tables for fine-grained RBAC

Revision ID: 4f5c5aa3de07
Revises: 26b579f2176d
Create Date: 2025-12-18 16:27:13.714867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5c5aa3de07'
down_revision: Union[str, None] = '26b579f2176d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)  # Disabled: already exists in SQLite
    # op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)  # Disabled: already exists in SQLite
    # op.alter_column('refresh_tokens', 'created_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=False)  # Disabled for SQLite compatibility
    # op.drop_index(op.f('idx_refresh_tokens_expires'), table_name='refresh_tokens')  # Disabled: index may not exist in SQLite
    # op.drop_index(op.f('idx_refresh_tokens_jti'), table_name='refresh_tokens')  # Disabled: index may not exist in SQLite
    # op.drop_index(op.f('idx_refresh_tokens_user'), table_name='refresh_tokens')  # Disabled: index may not exist in SQLite
    # op.create_index(op.f('ix_refresh_tokens_created_at'), 'refresh_tokens', ['created_at'], unique=False)  # Disabled: already exists in SQLite
    # op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)  # Disabled: already exists in SQLite
    # op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)  # Disabled: already exists in SQLite
    # op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)  # Disabled: already exists in SQLite
    # op.create_index(op.f('ix_refresh_tokens_revoked'), 'refresh_tokens', ['revoked'], unique=False)  # Disabled: already exists in SQLite
    # op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)  # Disabled: already exists in SQLite
    # op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)  # Disabled: already exists in SQLite
    # op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)  # Disabled: already exists in SQLite
    # op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)  # Disabled: already exists in SQLite
    # op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)  # Disabled: already exists in SQLite
    # op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)  # Disabled: already exists in SQLite
    # op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)  # Disabled: already exists in SQLite
    # op.create_index(op.f('ix_students_enrollment_date'), 'students', ['enrollment_date'], unique=False)  # Disabled: already exists in SQLite
    # op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)  # Disabled: already exists in SQLite
    # op.create_index(op.f('ix_students_is_active'), 'students', ['is_active'], unique=False)  # Disabled: already exists in SQLite
    # op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=True)  # Disabled: already exists in SQLite
    # op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)  # Disabled: already exists in SQLite
    # op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)  # Disabled: already exists in SQLite
    # op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)  # Disabled: already exists in SQLite
    # op.alter_column('users', 'is_active',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True,
    #            existing_server_default=sa.text('1'))  # Disabled for SQLite compatibility
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_index(op.f('ix_students_is_active'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_enrollment_date'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_revoked'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_created_at'), table_name='refresh_tokens')
    op.create_index(op.f('idx_refresh_tokens_user'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=1)
    op.create_index(op.f('idx_refresh_tokens_expires'), 'refresh_tokens', ['expires_at'], unique=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    # ### end Alembic commands ###
