"""add RBAC created_at columns

Revision ID: b6c5a7170d93
Revises: d37fb9f4bd49
Create Date: 2026-01-08 01:00:59.672863

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6c5a7170d93"
down_revision: Union[str, None] = "d37fb9f4bd49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add created_at column to role_permissions
    op.add_column("role_permissions", sa.Column("created_at", sa.DateTime(timezone=True), nullable=True))

    # Set default values for existing rows
    op.execute("UPDATE role_permissions SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")

    # Make it non-nullable after setting defaults
    with op.batch_alter_table("role_permissions") as batch_op:
        batch_op.alter_column("created_at", nullable=False)

    # Drop the old 'name' column from permissions if it exists, using batch mode for SQLite
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        # Check if column exists before dropping (in case migration ran partially)
        try:
            batch_op.drop_column("name")
        except Exception:
            pass  # Column may already be dropped
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("role_permissions", "created_at")
    # ### end Alembic commands ###
