"""add RBAC created_at columns

Revision ID: b6c5a7170d93
Revises: d37fb9f4bd49
Create Date: 2026-01-08 01:00:59.672863

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6c5a7170d93"
down_revision: Union[str, None] = "d37fb9f4bd49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add created_at column to role_permissions (idempotent for partially migrated DBs)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    rp_columns = {col["name"] for col in inspector.get_columns("role_permissions")}
    permissions_columns = {col["name"] for col in inspector.get_columns("permissions")}

    if "created_at" not in rp_columns:
        op.add_column("role_permissions", sa.Column("created_at", sa.DateTime(timezone=True), nullable=True))

    # Set default values for existing rows (whether column was just added or already present)
    op.execute("UPDATE role_permissions SET created_at = COALESCE(created_at, CURRENT_TIMESTAMP)")

    # Make it non-nullable after setting defaults
    with op.batch_alter_table("role_permissions") as batch_op:
        batch_op.alter_column("created_at", nullable=False)

    # Drop the old 'name' column from permissions if it exists, using batch mode for SQLite
    if "name" in permissions_columns:
        with op.batch_alter_table("permissions", schema=None) as batch_op:
            batch_op.drop_column("name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("role_permissions", "created_at")
    # ### end Alembic commands ###
