"""Add password_change_required field to users table

Revision ID: d377f961aa1f
Revises: 00c146dcf611
Create Date: 2025-11-23 21:57:42.942410

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d377f961aa1f"
down_revision: Union[str, None] = "00c146dcf611"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("password_change_required", sa.Boolean(), nullable=False, server_default=sa.text("FALSE"))
    )
    op.create_index(op.f("ix_users_password_change_required"), "users", ["password_change_required"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_password_change_required"), table_name="users")
    op.drop_column("users", "password_change_required")
    # ### end Alembic commands ###
