"""Update RBAC: enhance Permission model and add UserPermission

Revision ID: d37fb9f4bd49
Revises: 99perms_notifs_merge
Create Date: 2026-01-06 19:41:38.439526

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d37fb9f4bd49"
down_revision: Union[str, None] = "99perms_notifs_merge"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: notification_preferences and notifications tables already exist, skipping creation
    # NOTE: user_permissions table already exists, skipping creation

    # Check if old indexes exist before trying to drop them
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_indexes = {idx["name"] for idx in inspector.get_indexes("permissions")}

    # SQLite doesn't support ALTER COLUMN, so we'll use batch operations
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        # Add new columns
        batch_op.add_column(sa.Column("key", sa.String(length=100), nullable=True))  # nullable first for data migration
        batch_op.add_column(sa.Column("resource", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("action", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("is_active", sa.Boolean(), nullable=True, server_default="1"))
        batch_op.add_column(sa.Column("created_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))

        # Drop old indexes only if they exist
        if "idx_permissions_name" in existing_indexes:
            batch_op.drop_index("idx_permissions_name")
        if "ix_permissions_name" in existing_indexes:
            batch_op.drop_index("ix_permissions_name")

        # Create new indexes
        batch_op.create_index("idx_permissions_is_active", ["is_active"], unique=False)
        batch_op.create_index(
            "idx_permissions_key", ["key"], unique=False
        )  # Not unique yet, will be after data migration
        batch_op.create_index("idx_permissions_resource", ["resource"], unique=False)
        batch_op.create_index(batch_op.f("ix_permissions_is_active"), ["is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_permissions_key"), ["key"], unique=False)
        batch_op.create_index(batch_op.f("ix_permissions_resource"), ["resource"], unique=False)

    # Migrate existing permission data (if any exists)
    # Convert name format from 'resource.action' to 'resource:action' and populate new fields
    conn = op.get_bind()
    result = conn.execute(sa.text("SELECT id, name FROM permissions"))
    for row in result:
        perm_id, perm_name = row
        # Split on '.' for old format (e.g., 'students.read')
        if "." in perm_name:
            resource, action = perm_name.split(".", 1)
            key = f"{resource}:{action}"
        else:
            # Fallback for unexpected format
            resource = perm_name
            action = "unknown"
            key = perm_name

        conn.execute(
            sa.text("UPDATE permissions SET key = :key, resource = :resource, action = :action WHERE id = :id"),
            {"key": key, "resource": resource, "action": action, "id": perm_id},
        )

    # Now make columns non-nullable and drop old name column
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.alter_column("key", nullable=False)
        batch_op.alter_column("resource", nullable=False)
        batch_op.alter_column("action", nullable=False)
        batch_op.drop_column("name")

    # Add timestamp to role_permissions
    op.add_column("role_permissions", sa.Column("created_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse role_permissions changes
    op.drop_column("role_permissions", "created_at")

    # Reverse permissions table changes
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.VARCHAR(length=150), nullable=True))

        # Migrate data back: key → name
        conn = op.get_bind()
        result = conn.execute(sa.text("SELECT id, key FROM permissions"))
        for row in result:
            perm_id, perm_key = row
            # Convert 'resource:action' back to 'resource.action'
            perm_name = perm_key.replace(":", ".")
            conn.execute(
                sa.text("UPDATE permissions SET name = :name WHERE id = :id"), {"name": perm_name, "id": perm_id}
            )

        batch_op.alter_column("name", nullable=False)

        # Drop new indexes
        batch_op.drop_index(batch_op.f("ix_permissions_resource"))
        batch_op.drop_index(batch_op.f("ix_permissions_key"))
        batch_op.drop_index(batch_op.f("ix_permissions_is_active"))
        batch_op.drop_index("idx_permissions_resource")
        batch_op.drop_index("idx_permissions_key")
        batch_op.drop_index("idx_permissions_is_active")

        # Recreate old indexes
        batch_op.create_index("ix_permissions_name", ["name"], unique=True)
        batch_op.create_index("idx_permissions_name", ["name"], unique=True)

        # Drop new columns
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("is_active")
        batch_op.drop_column("action")
        batch_op.drop_column("resource")
        batch_op.drop_column("key")
    # ### end Alembic commands ###
