"""Add import/export tables for Feature #127 - Bulk Import/Export.

Revision ID: feature127_import_export
Revises: d37fb9f4bd49
Create Date: 2026-01-13 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "feature127_import_export"
down_revision = "d37fb9f4bd49"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_type", sa.String(length=10), nullable=False),
        sa.Column("import_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False, server_default="pending"),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("successful_rows", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("failed_rows", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("validation_errors", sa.JSON(), nullable=True),
        sa.Column("file_path", sa.String(length=500), nullable=True),
        sa.Column("imported_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["imported_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_import_job_created_at", "import_jobs", ["created_at"], unique=False)
    op.create_index("ix_import_job_import_type", "import_jobs", ["import_type"], unique=False)
    op.create_index("ix_import_job_status", "import_jobs", ["status"], unique=False)
    op.create_index("ix_import_jobs_id", "import_jobs", ["id"], unique=False)

    op.create_table(
        "import_rows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("import_job_id", sa.Integer(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("original_data", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False, server_default="pending"),
        sa.Column("error_messages", sa.JSON(), nullable=True),
        sa.Column("target_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["import_job_id"], ["import_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_import_row_import_job_id", "import_rows", ["import_job_id"], unique=False)
    op.create_index("ix_import_row_status", "import_rows", ["status"], unique=False)
    op.create_index("ix_import_rows_id", "import_rows", ["id"], unique=False)

    op.create_table(
        "export_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("export_type", sa.String(length=50), nullable=False),
        sa.Column("file_format", sa.String(length=10), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False, server_default="pending"),
        sa.Column("total_records", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("filters", sa.JSON(), nullable=True),
        sa.Column("scheduled", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("schedule_frequency", sa.String(length=50), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_export_job_created_at", "export_jobs", ["created_at"], unique=False)
    op.create_index("ix_export_job_export_type", "export_jobs", ["export_type"], unique=False)
    op.create_index("ix_export_job_status", "export_jobs", ["status"], unique=False)
    op.create_index("ix_export_jobs_id", "export_jobs", ["id"], unique=False)

    op.create_table(
        "import_export_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("operation_type", sa.String(length=50), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_import_export_history_operation", "import_export_history", ["operation_type"], unique=False)
    op.create_index("ix_import_export_history_timestamp", "import_export_history", ["timestamp"], unique=False)
    op.create_index("ix_import_export_history_user_id", "import_export_history", ["user_id"], unique=False)
    op.create_index("ix_import_export_history_id", "import_export_history", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_import_export_history_id", table_name="import_export_history")
    op.drop_index("ix_import_export_history_user_id", table_name="import_export_history")
    op.drop_index("ix_import_export_history_timestamp", table_name="import_export_history")
    op.drop_index("ix_import_export_history_operation", table_name="import_export_history")
    op.drop_table("import_export_history")

    op.drop_index("ix_export_jobs_id", table_name="export_jobs")
    op.drop_index("ix_export_job_status", table_name="export_jobs")
    op.drop_index("ix_export_job_export_type", table_name="export_jobs")
    op.drop_index("ix_export_job_created_at", table_name="export_jobs")
    op.drop_table("export_jobs")

    op.drop_index("ix_import_rows_id", table_name="import_rows")
    op.drop_index("ix_import_row_status", table_name="import_rows")
    op.drop_index("ix_import_row_import_job_id", table_name="import_rows")
    op.drop_table("import_rows")

    op.drop_index("ix_import_jobs_id", table_name="import_jobs")
    op.drop_index("ix_import_job_status", table_name="import_jobs")
    op.drop_index("ix_import_job_import_type", table_name="import_jobs")
    op.drop_index("ix_import_job_created_at", table_name="import_jobs")
    op.drop_table("import_jobs")
    # ### end Alembic commands ###
